### ISSUE TITLE
Move download buttons higher?

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng.org#11]
Instead of having them in the "Getting Started" section, how about under the social buttons? They feel like they belong closer to that area. Plus, they'd be visible without scrolling, and there's some empty area there.

**Comment by bazsi** [comment]
Maybe the links just below the github link could use some emphasis too. The
github link is probably primarily appreciated by developers, whereas our
users would probably be more interested in documentation/downloads.

**Comment by algernon** [comment]
@bazsi: Yeah, I agree. I'll open a separate issue about that, though, as it needs more thought.

I tried moving the buttons to a few places, but they looked awkward everywhere else, so I'll keep them where they are (and thus, close this issue).
