### ISSUE TITLE
Page publishing broken?

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng.org#20]
Although the latest merges finished, and travis [reported no error](https://travis-ci.org/balabit/syslog-ng.org), the gh-pages branch is not updated. I assume it failed because I set the tokens, and I do not have access to the repo anymore. A `set -e` to `build/travis-publish-gh-page.sh` could be useful, and a refresh of the token in `.travis.yml`.

**Comment by algernon** [comment]
Hrms. Not sure what the issues is, but the site does not update still :(

I borrowed the publish script from @attilammagyar, perhaps he can help?

**Comment by attilammagyar** [comment]
Does the new GH_TOKEN have access to the `public_repo` scope? (GitHub / Settings / Applications / Personal access tokens / Edit, the checkbox for `public_repo` needs to be checked. For my PET project, pushing to the `gh-pages` branch via this method from Travis-CI works fine with such settings.)

**Comment by lbudai** [comment]
public_repo was unchecked... 
It is checked now.

Thx for the hint.

**Comment by bazsi** [comment]
Hi,

It is still not updated.

**Comment by lbudai** [comment]
Yes, it is still not working... 
It is not clear what is the problem (token issue, I guess), algernon suggested that we could enable travis on other branches (not only master) and debug it on a feature branch...

**Comment by algernon** [comment]
If the token or its settings changed, you need to trigger a build to try the rebuild. IIRC that can be done from Travis, or from the GitHub hook settings.

**Comment by lbudai** [comment]
After every change I trigger the rebuild on Travis UI.

**Comment by algernon** [comment]
Oh! I found something!

Compare [this](https://travis-ci.org/balabit/syslog-ng.org/builds/31795054#L148) (which succeeded) and [this](https://travis-ci.org/balabit/syslog-ng.org/builds/39243582#L147). You can clearly see that the publish fails (there is no `Finished!` printed). Removing the redirection there will shed some light on what the problem is.

**Comment by lbudai** [comment]
Yes, we also found that.

(BTW I checked the original token and it worked for me for my branch
I think the problem is with the Travis encrypt/decrypt process (maybe I set a wrong value) ).

**Comment by attilammagyar** [comment]
@algernon FYI in the original script, I added the `/dev/null` redirects to make sure that `git` cannot accidentally print out the token, e.g. as part of a remote's URL it is pushing to or an error message or similar.

**Comment by lbudai** [comment]
@athos: after we figure out what is problem, I'll generate a shiny-new token
(and hope not start the debug process from the beginning :-) )

**Comment by attilammagyar** [comment]
@lbudai Of course, I just tried to explain why I put those debugging obstacles there in the first place.

(Also, be careful with @-mentioning, since my nickname on GitHub is @attilammagyar :-) )

**Comment by lbudai** [comment]
It is working now (the old, test-token removed, a new one is created and used).
The problem was that when I created the encrypted token, the environment variable name was missing, thus GH_TOKEN was not available.
The webpage seems OK for me.

**Comment by algernon** [comment]
\o/

Thanks!
